apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: luqo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: 381491960576.dkr.ecr.us-east-1.amazonaws.com/luqo-frontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: VITE_API_URL
          value: "http://backend-service:8000"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: luqo
spec:
  selector:
    app: frontend
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer   # ← Este crea un ALB en AWS automáticamente